// File generated by FlutterFire CLI (simplified for Android only)
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoVJOeSjZaraF_K5AHtcv9qFhqIZOiyCs',
    appId: '1:380861290492:android:e20b0bd6c00e371f994479',
    messagingSenderId: '380861290492',
    projectId: 'fyp2-92b3f',
    storageBucket: 'fyp2-92b3f.firebasestorage.app',
  );
}
